@host = localhost:8080
// Register User
// @name register
POST https://{{host}}/api/user/register HTTP/1.1
content-type: application/json
    
{
    "name": "Yang Kun",
    "username": "yangwawa0323",
    "email": "yangwawa0323@163.com",
    "password": "123465789"
}

###
// @name login
POST https://{{host}}/api/user/login HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{register.response.body.$.token}}

## Please commit two time to detect the unique username and mail
POST https://{{host}}/api/user/register HTTP/1.1
content-type: application/json
    
{
    "name": "Wang yin qi2",
    "username": "wyq750323",
    "email": "wangyq750323@163.com",
    "password": "123465789",
    "user_class": 1
}

###

GET https://{{host}}/api/user/25/activate-by-email?token=%242a%2410%24iuPizsiVSpehR6rmMCjt2uwFgA9kEUQWcwhYT6iBHTn3.r411fa7O

###

GET https://localhost:8080/api/user/30/activate-by-email?token=%242a%2410%24je4qEzNg%2FF%2Fl83wpYuNPDufsuNVo9OtePfZuJPEgeQYmbwlOf8xrC