@host = localhost:8080
// Register User
POST http://{{host}}/api/user/register HTTP/1.1
content-type: application/json
    
{
    "name": "Yang Kun",
    "username": "yangwawa0323",
    "email": "yangwawa0323@163.com",
    "password": "123465789"
}